In [1]:
# Imports:
#  - z_normalize(X, X_mean=None, X_std=None)
#  - gen_synth_norm_data(B,n=100,S_YdotX=None,X_range=(0,10),X_are_ints=True)
#  - estimate_model_params(X,Y)
#  - gen_synth_sub_data(B, n, epsilon, X_range, X_mean, X_std, X_are_ints=True)
#  - single_subject_eval(x_obs, y_obs, B, R, S_YdotX, X_mean, X_std)

from normstats import *
np.set_printoptions(suppress=True)

In [2]:
# Parameters for normative synthetic data generation

# number of samples
n = 1000
# number of ind vars
k = 3
# number of dep vars
m = 2
# std_dev of noise
S_YdotX_actual = np.random.uniform(1.0, 2.0, size=(m))

# B (model params) will be chosen randomly from this range
B_range = (100, 200)
B_actual = np.random.randint(B_range[0], B_range[1], size=(m, k+1))
#B = np.random.uniform(B_range[0], B_range[1], size=(m, k+1))
        
# X (ind vars) will be chosen randomly from this range
X_range = (1,20)
X_are_ints = True

In [3]:
# Generate synthetic normative dataset
X, Y, epsilon_actual = gen_synth_norm_data(B_actual, n, S_YdotX_actual, X_range, X_are_ints=X_are_ints)

# estimate model params from synthetic dataset
B_estimate, S_YdotX_estimate, R, X_mean, X_std = estimate_model_params(X,Y)

In [4]:
print('B_actual:')
print(B_actual)
print()
print('B_estimate')
print(B_estimate)
print()
print('S_YdotX_actual')
print(S_YdotX_actual)
print()
print('S_YdotX_estimate')
print(S_YdotX_estimate)

B_actual:
[[142 102 106 167]
 [105 150 106 182]]

B_estimate
[[141.96951796 102.02249235 105.96064707 167.03355208]
 [104.98130888 150.01068629 106.00275257 182.03398295]]

S_YdotX_actual
[1.16075062 1.21386225]

S_YdotX_estimate
[1.15499449 1.23741014]


In [5]:
# Generate a single perfectly median subject
x_obs, y_obs = gen_synth_sub_data(B_actual, 1, 0.0, X_range, X_mean, X_std, X_are_ints=X_are_ints)

In [6]:
print(x_obs)
print(y_obs)
print(S_YdotX_estimate)

[[ 7]
 [ 7]
 [19]]
[[192.37643685]
 [200.90868642]]
[1.15499449 1.23741014]


In [7]:
p, t_diff = single_subject_eval(x_obs, y_obs, B_estimate, R, S_YdotX_estimate, n, X_mean, X_std)

In [8]:
print(f'p: {p}')

p: [[0.5084326  0.48612612]]
