In [48]:
import logging
import sys
from normstats import *
np.set_printoptions(suppress=True)

logging.basicConfig(
    # Change the logging level to DEBUG to get a lot more verbosity
    #level=logging.DEBUG,
    level=logging.WARN,
    format='%(asctime)s - %(name)s - %(funcName)s - %(levelname)s - %(message)s',
    stream=sys.stdout,
    force=True
)
logger = logging.getLogger(__name__)

# For reproducibility
np.random.seed(abs(hash("giraffes are cool"))%(2**32 - 1))

In [49]:
# Parameters for normative synthetic data generation

# number of samples
n = 10
# number of ind vars
k = 3
# number of dep vars
m = 2
# std_dev of noise
S_YdotX_actual = np.random.uniform(10.0, 20.0, size=(m))

# B (model params) will be chosen randomly from this range
B_range = (100, 200)
#B_actual = np.random.randint(B_range[0], B_range[1], size=(m, k+1))
B_actual = np.random.uniform(B_range[0], B_range[1], size=(m, k+1))
        
# X (ind vars) will be chosen randomly from this range
X_range = (1,20)
X_range_syth = (5,15)
X_are_ints = True

In [50]:
# Generate synthetic normative dataset
X, Y, epsilon_actual = gen_synth_norm_data(B_actual, n, S_YdotX_actual, X_range, X_are_ints=X_are_ints)

# estimate model params from synthetic dataset
B_estimate, S_YdotX_estimate, R, X_mean, X_std = estimate_model_params(X,Y)

In [51]:
print('B_actual:')
print(B_actual)
print()
print('B_estimate')
print(B_estimate)
print()
print('S_YdotX_actual:')
print(S_YdotX_actual)
print()
print('S_YdotX_estimate:')
print(S_YdotX_estimate)

B_actual:
[[158.58437182 176.18008607 156.37639273 142.15113047]
 [144.98971425 101.36918127 114.66956827 169.47798428]]

B_estimate
[[159.30992403 180.06475614 158.31146769 141.82749468]
 [147.17921962 100.5709996  110.06973254 162.59882055]]

S_YdotX_actual:
[15.56876998 11.94381454]

S_YdotX_estimate:
[[14.39139734]
 [ 7.97953417]]


In [52]:
# Generate a single perfectly median subject
x_obs, y_obs = gen_synth_sub_data(B_actual, 1, 0.0, X_range_syth, X_mean, X_std, X_are_ints=X_are_ints)

In [53]:
p, p_ci = single_subject_eval(x_obs, y_obs, B_estimate, R, S_YdotX_estimate, n, X_mean, X_std)

In [54]:
# Should be ~0.5 since it's a perfectly median subject
print('p')
print(p[:,0])
print('lower confidence interval of p')
print(p_ci[:,0])
print('upper confidence interval of p')
print(p_ci[:,1])

p
[0.5204087  0.88336542]
lower confidence interval of p
[0.26537543 0.63663998]
upper confidence interval of p
[0.76890115 0.99204168]
